# 5 测试

> 概念：测试驱动 Test driven。关键是巨细无遗的思想。

![image-20200706111031036](https://pic-1301887806.cos.ap-guangzhou.myqcloud.com/img/image-20200706111031036.png)

## 引发错误

polls/<u>models</u>.py 定义 Question 新方法 was_published_recently() 判断 Question 对象是否过去一天之内创建的。

:information_source: 教程中似乎缺少这部分，导致报错。

```python
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):...

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
```

## 编写测试文件

polls/<u>tests</u>.py

```python
import datetime

from django.test import TestCase
from django.utils import timezone

from .models import Question


class QuestionModelTests(TestCase):

    def test_was_published_recently_with_future_question(self):
        """
        was_published_recently() returns False for questions whose pub_date
        is in the future.
        """
        time = timezone.now() + datetime.timedelta(days=30)
        future_question = Question(pub_date=time)
        self.assertIs(future_question.was_published_recently(), False)
```

然后运行 `py manage.py test polls` 即可看到结果（报错）。

❓ 看起来测试的命令行是 py manage.py test <u>\<app名></u> [^ test cli]

程序内部，自动化测试的流程为：

```flow
type: flow
op1=>operation: 在app文件夹里找tests.py
op2=>operation: 在tests.py中 找子类 class XXX(TestCase)
op3=>operation: 创建特殊的测试用数据库
op4=>operation: 找到并运行子类XXX中以 test 开头的方法
cond=>condition: 根据 test 方法的断言
assertIs()判断
t=>end: OK
f=>end: FAIL


op1->op2->op3->op4->cond

cond(yes)->t
cond(no)->f
```

## 修复错误

根据错误提示，重新编写 models.py 中的出错方法：

```python
def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now
```

再次运行 `py manage.py test polls` OK。

## 完善测试代码

再给测试类添加两个方法，检测一天前和一天内的对象 是否正确地分别返回 False 和 True。确保全面彻底。

## 测试视图

### Client工具

Client 用来模拟用户和视图层的交互。

```shell
>>> py manage.py shell
>>> from django.test.utils import setup_test_environment
>>> setup_test_environment()

>>> from django.test import Client
>>> # create an instance of the client for our use
>>> client = Client()

>>> # get a response from '/'
>>> response = client.get('/')
Not Found: /
>>> # we should expect a 404 from that address; if you instead see an
>>> # "Invalid HTTP_HOST header" error and a 400 response, you probably
>>> # omitted the setup_test_environment() call described earlier.
>>> response.status_code
404
>>> # on the other hand we should expect to find something at '/polls/'
>>> # we'll use 'reverse()' rather than a hardcoded URL
>>> from django.urls import reverse
>>> response = client.get(reverse('polls:index'))
>>> response.status_code
200
>>> response.content
b'\n    <ul>\n    \n        <li><a href="/polls/1/">What&#x27;s up?</a></li>\n    \n    </ul>\n\n'
>>> response.context['latest_question_list']
<QuerySet [<Question: What's up?>]>
```



## ❓

[^ test cli]: 测试的命令行是 py manage.py test <u>\<app名></u> ？

